### ISSUE TITLE
PlotMe limit not working

### ISSUE THREAD

**Issue by tattyseal** [WorldCretornica/PlotMe-Core#134]
Hello, I am working on a PlotMe server. But I can claim as many plots as I want (deopped, with the rank I have set the perms to) even though I have assigned plotme.use (which should assign a limit of 1). I am using permissionsex, and when I do /plot it shows 0 out of 1 plots claimed, even though I had claimed 6.

My Permissions File:
```
groups:
  User:
    options:
      prefix: '&e[&6User&e]&f '
      default: true
    permissions:
    - plotme.use
    - multiverse.access.Creative
    - multiverse.access.world_end
    - multiverse.access.world_nether
    - multiverse.access.hub
    - multiverse.access.world
    - multiverse.portal.access.toHubFromSurvival
    - multiverse.portal.access.toHubFromCreative
    - multiverse.portal.access.toSurvival
    - multiverse.portal.access.toCreative
    - factions.kit.rank0
    - essential
    - essentials.back
    - essentials.back.ondeath
    - essentials.balance
    - essentials.balance.others
    - essentials.balancetop
    - essentials.compass
    - essentials.delhome
    - essentials.depth
    - essentials.help
    - essentials.home
    - essentials.ignore
    - essentials.list
    - essentials.mail
    - essentials.mail.send
    - essentials.motd
    - essentials.msg
    - essentials.msg.format
    - essentials.pay
    - essentials.ping
    - essentials.rules
    - essentials.sell
    - essentials.sethome
    - essentials.sethome.multiple
    - essentials.signs.use.*
    - essentials.spawn
    - essentials.suicide
    - essentials.time
    - essentials.tpa
    - essentials.tpaccept
    - essentials.tpahere
    - essentials.tpdeny
    - essentials.who
  TrialMod:
    options:
      prefix: '&a[&2Trial_Mod&a] &f'
    inheritance:
    - RedstonePlayer
  Demi-Mod:
    options:
      prefix: '&d[&5Demi-Mod&d] &f'
    inheritance:
    - TrialMod
  Moderator:
    options:
      prefix: '&e[&6Moderator&e] &f'
    inheritance:
    - Demi-Mod
  Demi-Admin:
    options:
      prefix: '&b[&9Demi-Admin&b] &f'
    inheritance:
    - Moderator
  Admin:
    options:
      prefix: '&4[&cAdmin&4] &f'
    inheritance:
    - Demi-Admin
  HeadAdmin:
    options:
      prefix: '&6[&5Head_Admin&6] &f'
    inheritance:
    - Admin
  Owner:
    options:
      prefix: '&2[&aOwner&2]'
    inheritance:
    - HeadAdmin
  playgrid.membership.staff:
    permissions:
    - playgrid.command.ban
  playgrid.membership.admin:
    permissions:
    - playgrid.command.ban
  RedstonePlayer:
    inheritance:
    - User
schema-version: 1
users:
  tattyseall:
    permissions:
    - '*'
  154b4d36-8b87-4a4a-8fbc-729466e11a3e:
    permissions:
    - '*'
    options:
      name: MINECRAFTmark150
      prefix: '&a[&2Owner&a] &6[&ePlugin_Developer&6]'
    group:
    - Owner
    worlds:
      '&6[&ePlugin_Developer&6]':
        options:
          prefix: '"&a[&2Owner&a]'
  ff4fd97a-31bb-42f5-add0-052137a0331f:
    permissions:
    - '*'
    options:
      name: DePowah
  e1949d31-4f97-423a-8229-690fd6756b1c:
    permissions: []
    options:
      name: Rushmead
      prefix: ''
    group:
    - DemiAdmin
  b369fb84-9a71-46b7-9741-c3bdbf31eda8:
    group:
    - HeadAdmin
    options:
      name: JJGal12
      prefix: '&5[&6Dragon_Keeper&5] &6[&5Head_Admin&6]'
  b85358ba-e516-4e09-bd24-4f40f4b8c7ab:
    group:
    - Admin
    options:
      name: BigBadBrick
      prefix: '&3[&9Web_Developer&3] &4[&cAdmin&4]'
      suffix: ''
    worlds:
      Developer&c]&f:
        options:
          suffix: '&c[&9Web'
  06afedea-0239-4fab-aaeb-03080dac92d2:
    group:
    - HeadAdmin
    options:
      name: rockstarblue012
      prefix: '&6[&5Head_Admin&6] &4[M&fL&1G&4]'
    worlds:
      '&4[M&fL&1':
        options:
          prefix: '&6[&5Head_Admin&6]'
    permissions: []
  7956cdd3-e075-4595-a045-2479b35a3570:
    permissions:
    - permissions.*
    options:
      name: tattyseal
    group:
    - User
```

I am using the group user, and as you can see it has plotme.use. I am using the latest version from BukkitDev.

**Comment by MattBDev** [comment]
Can you give me your server log? Preferebly a hastebin.com link of it.

**Comment by tattyseal** [comment]
http://hastebin.com/rabazasoko.vhdl

**Comment by MattBDev** [comment]
Can I also see your plotme config?

**Comment by MattBDev** [comment]
Why do you have two worlds with the same name?
'[22:56:23] [Server thread/INFO]: [PlotMe-DefaultGenerator] Importing world Creative from PlotMe
[22:56:23] [Server thread/INFO]: [PlotMe-DefaultGenerator] Importing world creative from PlotMe'
Also, you don't need DynmapPlotMe if you aren't using the Dynmap plugin... :expressionless:

**Comment by MattBDev** [comment]
Please use your permission plugin to check for this `plotme.limit.1` and if it says true then just keep checking for a number higher up. If it still says true, then you have a permissions issue.

**Comment by tattyseal** [comment]
I meant to install Dynmap, and the 2 world names were not added by me, I will remove those

```
usemySQL: false
mySQLconn: jdbc:mysql://localhost:3306/minecraft
mySQLuname: root
mySQLpass: password
globalUseEconomy: false
allowWorldTeleport: true
defaultWEAnywhere: false
NbClearSpools: 3
NbBlocksPerClearStep: 50000
AdvancedLogging: false
worlds:
  creative:
    PlotAutoLimit: 1000
    DaysToExpiration: 7
    ProtectedBlocks:
    - 54
    - 61
    - 54
    - 62
    - 120
    - 94
    - 93
    - 84
    - 25
    - 355
    - 118
    - 117
    - 138
    - 140
    - 145
    - 154
    - 23
    - 158
    PreventedItems:
    - '351:15'
    - '259'
    - '328'
    - '343'
    - '342'
    - '333'
    economy:
      UseEconomy: false
      CanPutOnSale: false
      RefundClaimPriceOnReset: false
      RefundClaimPriceOnSetOwner: false
      ClaimPrice: 0.0
      ClearPrice: 0.0
      AddPlayerPrice: 0.0
      DenyPlayerPrice: 0.0
      RemovePlayerPrice: 0.0
      UndenyPlayerPrice: 0.0
      PlotHomePrice: 0.0
      SellToPlayerPrice: 0.0
      BiomeChangePrice: 0.0
      ProtectPrice: 0.0
      DisposePrice: 0.0
    AutoLinkPlots: true
    DisableExplosion: true
    DisableIgnition: true
    UseProgressiveClear: false
    NextFreed: -4;-2
  Creative:
    PlotAutoLimit: 1000
    DaysToExpiration: 7
    ProtectedBlocks:
    - 54
    - 61
    - 54
    - 62
    - 120
    - 94
    - 93
    - 84
    - 25
    - 355
    - 118
    - 117
    - 138
    - 140
    - 145
    - 154
    - 23
    - 158
    PreventedItems:
    - '351:15'
    - '259'
    - '328'
    - '343'
    - '342'
    - '333'
    economy:
      UseEconomy: false
      CanPutOnSale: false
      RefundClaimPriceOnReset: false
      RefundClaimPriceOnSetOwner: false
      ClaimPrice: 0.0
      ClearPrice: 0.0
      AddPlayerPrice: 0.0
      DenyPlayerPrice: 0.0
      RemovePlayerPrice: 0.0
      UndenyPlayerPrice: 0.0
      PlotHomePrice: 0.0
      SellToPlayerPrice: 0.0
      BiomeChangePrice: 0.0
      ProtectPrice: 0.0
      DisposePrice: 0.0
    AutoLinkPlots: true
    DisableExplosion: true
    DisableIgnition: true
    UseProgressiveClear: false
    NextFreed: 0;0
```

And I will check the permissions too. Like I said, when I do /plot it does say 0 out of 1 (or how many are set in permissions) but it lets me claim as many as I want
